language: python
env:
  - PYTHON_VERSION=3.7
before_install:
    - wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p /home/travis/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes --quiet conda
install:
    - conda create -n testenv --yes pip python=$PYTHON_VERSION
    - source activate testenv
    - pip install --yes -r requirements.txt
script:
    - flake8 *.py
    - python prepare_data.py
notifications:
  email: true
